image: 
  file: .gitpod.Dockerfile

tasks:
  - init: 'composer create-project laravel/laravel  laravel'

ports:
  - port: 8080
    visibility: public

vscode:
  extensions:
    - felixfbecker.php-debug

